### ISSUE TITLE
Migrating to Django>=3

### ISSUE THREAD

**Issue by Milutinke92** [Sinkler/django-radiogrid#4]
Hi, is there a possibility to upgrade this package to work with Django>=3?
Thanks

**Comment by Sinkler** [comment]
Hello! I'll manage it soon, thank you!

**Comment by Milutinke92** [comment]
@Sinkler also you must change `from_db_value` - remove `context` as required argument

**Comment by Sinkler** [comment]
@Milutinke92 thanks a lot, I nailed it, please check a new version https://pypi.org/project/django-radiogrid/1.1.0/
